Gridstack layout
netuitive-community-packages/netuitive-packages-kafka pull request #8
Opened 2017-02-24 19:59 UTC by markstarbuck

Closes #7

2017-02-25 19:24 UTC, Grumblesmith requested changes
I tested provisioning with this expanded layout section, and it failed to deserialize. Could you revert that change?

2017-02-27 15:24 UTC, markstarbuck commented
@Createor layout reverted; does it serialize?

2017-02-27 15:35 UTC, Createor commented
Yeah, looks good

2017-02-27 15:35 UTC, Grumblesmith approved these changes

2017-02-27 16:13 UTC, merged